site_name: Spool
site_description: Send mails with YAML.
site_author: 'Daniel Besmer'
site_url: 'https://besmerd.github.io/spool'

repo_name: 'besmerd/spool'
repo_url: 'https://github.com/besmerd/spool'

theme:
  name: 'material'
  logo:
    icon: 'mail'

markdown_extensions:
  - admonition
  - codehilite
  - markdown.extensions.def_list
