site_name: Spool
site_description: Send mails with YAML.
site_author: Daniel Besmer
site_url: https://besmerd.github.io/spool

repo_name: besmerd/spool
repo_url: https://github.com/besmerd/spool

nav:
  - index.md
  - installation.md
  - examples.md
  - reference.md
  - api.md
  - changelog.md

theme:
  name: material
  icon:
    logo: material/mailbox

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - markdown.extensions.def_list
